### ISSUE TITLE
Plugin does not geocode anymore if only street has been filled out

### ISSUE THREAD

**Issue by freshface** [riasvdv/statamic-address-field#3]
When only entering the street; 'Grote Markt 5' it geocodes, but it doesn't take into account the zip, city, country because there is allready a lat en lon coordinate. There are multiple 'Grote Markt 5' in belgium.

This line should be removed https://github.com/riasvdv/statamic-address-field/blob/fb9524bdaafc1a4c093c0729845fe515d150f719/resources/js/components/fieldtypes/Address.vue#L138

**Comment by riasvdv** [comment]
I'll take a look at this soon, it does seem like a bug in that case. Thanks for reporting this
